### PR TITLE
Dump & Restore project in scripts

### PR DESCRIPTION
**Pull request by iLLiCiTiT**
## Description
Added commands in manage scripts to dump and restore project from database.

### CODE REVIEW

**Review by martastain — DISMISSED** [review]
Can't test the PowerShell, but I trust you entirely :)

**Comment by martastain** [comment]
BTW: that part where the insert statement is searched for - if I understand it correctly, it only greps projectname without single quotes.

If there are projects `project1` and `project10`, it would dump both project records from `public.project` if you try to backup just project1.

The solution i use in the makefile is just quoting the string, so it searches for `'project1'`. Maybe even better would be to look for `VALUES ('project1', ` since the project name is always the first value in the insert statement. just quoting does not handle cases, when there's something like `{"description": "this project is exactly like 'project1'. hooray"}` in `project10`'s  attributes.

**Comment by iLLiCiTiT** [comment]
> BTW: that part where the insert statement is searched for - if I understand it correctly, it only greps projectname without single quotes.

Fixed

**Comment by rontown** [comment]
Is this available in the web UI and does it still need to be rolled into the docker build?

**Comment by martastain** [comment]
These are just command line options. which don't affect backend or frontend in any way. We'll examine options to do this using the UI, but at this point, these script just dump project related data to a single SQL file (and restore this file back to the database).

On linux, you run `make dump projectname=<yourprojectname>` to create `dump.<projectname>.sql` file in the ayon-docker directory and then `make restore projectname=<yourprojectname>` takes the file and pushes it back (original project in the database will be overwritten.

On windows i suspect the syntax is slightly different `./manage.ps1 dump <yourprojectname>` and `./manage.ps1 restore <youprojectname>` respectively.

**Pull request merged**
